### ISSUE TITLE
Download historic data

### ISSUE THREAD

**Issue by sunils27** [seligman/cloud_sizes#1]
A request more than an issue:

Is it possible to download historic data?

**Comment by seligman** [comment]
I have [historical data available for AWS](https://github.com/seligman/aws-ip-ranges/tree/master/history)

However I only started tracking the other providers in this repo on 2021-08-14, so no historical data available yet.  Once the year rolls over, I'll gather what history I've gathered for 2021 in a separate check in like I did for the AWS repo.

**Comment by seligman** [comment]
Added historical data with 6b7bbb201b6cd7b052e26de9e82ee7682dec66ab
